# docker-compose で使用するバージョンを定義しています。2023年1月時点では、3.9が最新です。
version: "3.9"
services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
